export const PRETTIER_OPTIONS = [
  'printWidth',
  'tabWidth',
  'useTabs',
  'semi',
  'singleQuote',
  'jsxSingleQuote',
  'trailingComma',
  'bracketSpacing',
  'bracketSameLine',
  'jsxBracketSameLine',
  'rangeStart',
  'rangeEnd',
  'requirePragma',
  'insertPragma',
  'proseWrap',
  'arrowParens',
  'htmlWhitespaceSensitivity',
  'endOfLine',
  'quoteProps',
  'vueIndentScriptAndStyle',
  'embeddedLanguageFormatting',
  'singleAttributePerLine',
] as const;
